Rahbaran Andishe/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rahbaran_Andishe.Models;

namespace Rahbaran_Andishe.Controllers
{
    //[Authorize]
    public class AdminController : Controller
    {
        // GET: Admin
        private SiteDb _db;
        public AdminController()
        {
            _db = new SiteDb();
        }
        public ActionResult Index()
        {
            return View();
        }
    }
}

Rahbaran Andishe/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rahbaran_Andishe.Models;

namespace Rahbaran_Andishe.Controllers
{
    public class ProductController : BaseAdminController
    {
        // GET: Product
        public ActionResult Index()
        {
            var model = Db.Forms.ToList();
            return View(model);
        }

        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Form model, HttpPostedFileBase img)
        {
            var dbase = new SiteDb();
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            Db.Forms.Add(model);
            Db.SaveChanges();
            Success("عملیات درج با موفقیت انجام شد");
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var model = Db.Forms.Find(id);

            if (model == null)
            {
                NotFount();
                return RedirectToAction("Index");
            }

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Form product, HttpPostedFileBase img)  
        {
            var model = Db.Forms.Find(product.Id);

            if (model == null)
            {
                NotFount();
                return RedirectToAction("Index");
            }

            Db.SaveChanges();
            Success();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var model = Db.Forms.Find(id);

            Db.Forms.Remove(model);
            Db.SaveChanges();
            Success();
            return RedirectToAction("Index");
        }
    }
}

Rahbaran Andishe/Controllers/SliderController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rahbaran_Andishe.Models;

namespace Rahbaran_Andishe.Controllers
{
    public class SliderController : BaseAdminController
    {
        // GET: Slider
        public ActionResult Index()
        {
            var model = Db.Sliders.ToList();
            return View(model);
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(Slider model, HttpPostedFileBase img)
        {
            if (!ModelState.IsValid)
            {
                Danger("لطفا ورودی ها را چک کنید");
                return View(model);
            }
            if (img.ContentLength <= 0)
            {
                Danger("فایل آپلود شده معتبر نمیباشد");
            }

            var name = img.FileName;
            var guid = Guid.NewGuid();
            var newName = $"{guid}-{name}";

            var path = Path.Combine(Server.MapPath("~/Storage"), newName);
            img.SaveAs(path);
            Success();
            model.Img = newName;
            Db.Sliders.Add(model);
            Db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            var model = Db.Sliders.Find(id);

            if (model == null)
            {
                NotFount();
                return RedirectToAction("Index");
            }

            return View(model);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Slider model, HttpPostedFileBase img)
        {
            var dbmodel = Db.Sliders.Find(model.Id);

            if (dbmodel == null)
            {
                NotFount("خطا متاسفانه چنین آیتمی پیدا نشد");
                return RedirectToAction("Index");
            }


            if (img != null)
            {
                var oldName = dbmodel.Img;

                var oldPath = Request.MapPath("~/Storage/" + oldName);
                if (System.IO.File.Exists(oldPath))
                {
                    System.IO.File.Delete(oldPath);
                }

                var name = img.FileName;
                var guid = Guid.NewGuid();
                var newName = $"{guid}-{name}";

                var path = Path.Combine(Server.MapPath("~/Storage"), newName);
                img.SaveAs(path);
                Success();
                Db.SaveChanges();

            }

            dbmodel.Description = model.Description;


            Db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult Delete(int id)
        {
            var dbmodel = Db.Sliders.Find(id);

            if (dbmodel == null)
            {
                NotFount("خطا متاسفانه چنین آیتمی پیدا نشد");
                return RedirectToAction("Index");
            }

            var fileName = dbmodel.Img;
            var oldPath = Request.MapPath("~/Storage/" + fileName);
            if (System.IO.File.Exists(oldPath))
            {
                System.IO.File.Delete(oldPath);
            }
            Db.Sliders.Remove(dbmodel);
            Db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Rahbaran Andishe/Views/Shared/_AdminLayout.cshtml
@using WebApplication1.Infra.Keys
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta content="" name="description" />
    <meta content="" name="author" />

    <meta name="viewport" content="width=device-width" />
    <title></title>
    <link href="~/Content/Content/jquery-ui/jquery-ui-1.10.1.custom.css" rel="stylesheet" />
    <link href="~/Content/Content/bootstrap-rtl.css" rel="stylesheet" />
    <link href="~/Content/Content/bootstrap-reset.css" rel="stylesheet" />
    <link href="~/Content/Content/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/Content/bootstrap-fileupload/bootstrap-fileupload.css" rel="stylesheet" />
    <link href="~/Content/Scripts/js/data-tables/DT_bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Content/style.css" rel="stylesheet" />
    <link href="~/Content/Content/style-responsive.css" rel="stylesheet" />

    <script src="~/Content/Scripts/modernizr-2.8.3.js"></script>

    <!--This bundle was moved by the Telerik VS Extensions for compatibility reasons-->
    <script src="~/Content/Scripts/jquery-2.1.4.js"></script>

</head>

<body>
    <div class="k-rtl">
        <section id="container">
            <!--header start-->
            <header class="header fixed-top clearfix">
                <div style="width: 80%; height: 80px; float: left;">
                    <a href="@Url.Action("index","Home")">
                    <img src="~/Content/image/logo-mobinnet.png" style="float: left; margin-top: 25px; margin-left: 4%;"/>
                    </a>
                </div>
                <!--logo start-->
                <div class="brand">
                    <a href="@Url.Action("index","Admin")" class="logo">
                        بخش مدیریت سایت
                    </a>
                    <div class="sidebar-toggle-box">
                        <div id="MenuRight" class="fa fa-bars"></div>
                    </div>
                </div>
                <!--logo end-->
            </header>
            <!--header end-->
            <aside>
                <div id="sidebar" class="nav-collapse">
                    <!-- sidebar menu start-->
                    <div class="leftside-navigation">
                        <ul class="sidebar-menu" id="nav-accordion">
                            <li>
                                <a class="active" href="@Url.Action("Index","Admin")">
                                    <i class="fa fa-dashboard"></i>
                                    <span>داشبورد</span>
                                </a>
                            </li>
                            <li class="sub-menu">
                                <a href="javascript:;">
                                    <i class="fa fa-laptop"></i>
                                    <span>محصولات</span>
                                </a>
                                <ul class="sub">
                                    <li><a href="@Url.Action("Index","Product")">لیست محصولات</a></li>
                                    <li><a href="@Url.Action("Add","Product")">افزودن محصول</a></li>
                                </ul>
                            </li>
                            <li class="sub-menu">
                                <a href="javascript:;">
                                    <i class="fa fa-image"></i>
                                    <span>اسلایدر</span>
                                </a>
                                <ul class="sub">
                                    <li><a href="@Url.Action("Index","Slider")">لیست اسلایدر ها</a></li>
                                    <li><a href="@Url.Action("Add","Slider")">افزودن اسلایدر</a></li>
                                </ul>
                            </li>
                            @*<li class="sub-menu">
                                <a href="javascript:;">
                                    <i class="fa fa-paperclip"></i>
                                    <span>صفحات</span>
                                </a>
                                <ul class="sub">
                                    <li><a href="./AdminPageGroups">مدیریت گروه های صفحات</a></li>
                                    <li><a href="./AdminPages">مدیریت صفحات</a></li>
                                </ul>
                            </li>*@
                            @*<li class="sub-menu">
                                <a href="javascript:;">
                                    <i class="fa fa-comments"></i>
                                    <span>نظرات</span>
                                </a>
                                <ul class="sub">
                                    <li><a href="./AdminComments">مدیریت کامنت ها</a></li>
                                </ul>
                            </li>*@
                            @*<li class="sub-menu">
                                <a href="javascript:;">
                                    <i class="fa fa-archive"></i>
                                    <span>کالا</span>
                                </a>
                                <ul class="sub">
                                    <li><a href="./AdminProductGroups">مدیریت گروه های کالاها</a></li>
                                    <li><a href="./AdminProducts">مدیریت کالاها</a></li>
                                    <li><a href="./Brands">مدیریت برند ها</a></li>

                                </ul>
                            </li>*@
                        </ul>
                    </div>
                    <!-- sidebar menu end-->
                </div>
            </aside>
            <section id="main-content">
                <section class="wrapper">
                    <div class="row">
                        <div class="col-md-12">
                            @if (TempData[Constants.MessageKey] != null)
                            {
                                <div class="alert alert-@TempData[Constants.ColorKey]">@TempData[Constants.MessageKey]</div>    
                            }
                            @RenderBody()
                        </div>
                    </div>
                </section>

            </section>
        </section>
    </div>
    <script src="~/Content/Scripts/jquery-ui-1.11.2.js"></script>
    <script src="~/Content/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Content/Scripts/jquery.validate.js"></script>
    <script src="~/Content/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Content/Scripts/bootstrap-fileupload.js"></script>
    <script src="~/Content/Scripts/bootstrap-rtl.js"></script>
    <script src="~/Content/Scripts/jquery.dcjqaccordion.2.7.js"></script>
    <script src="~/Content/Scripts/jquery.scrollTo.js"></script>
    <script src="~/Content/Scripts/jquery.nicescroll.js"></script>
    <script src="~/Content/Scripts/jquery.scrollTo/jquery.scrollTo.js"></script>
    <script src="~/Content/Scripts/js/data-tables/jquery.dataTables.js"></script>
    <script src="~/Content/Scripts/js/data-tables/DT_bootstrap.js"></script>
    <script src="~/Content/Scripts/js/scripts.js"></script>
    <script src="~/Content/Scripts/js/table-editable.js"></script>
    <script src="~/Content/Scripts/eshop.js"></script>

    <script src="~/Content/Scripts/bootstrap-rtl.js"></script>
    <script src="~/Content/Scripts/respond.js"></script>


    <script>
        $(document).ready(function () {
            EditableTable.init();
            $("form").addClass("form-horizontal").attr("role", "form");
            $("#buttons * *").addClass("btn btn-primary");
            $('input[type="text"],input[type="datetime"],input[type="password"],textarea,select').addClass("form-control");
        });
    </script>
</body>

<!-- END BODY -->
</html>

Rahbaran Andishe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">  
    <title>راهبران اندیشه</title>
    <link type="text/css" rel="stylesheet" href="~/Content/css/plugin.css">
    <link type="text/css" rel="stylesheet" href="~/Content/css/main.css" />
    <link rel="shortcut icon" href="~/Content/img/logo/LOGO-new.png">
    <meta charset="UTF-8">
    <meta name="description" content="راهبران اندیشه طلاع رسانی در زمینه استفاده از متد های نوین فناوری اطلاعات و ارتباطات در مشاغل متفاوت">
    <meta name="author" content="امید ابراهیمی">
</head>
<body>
    <!--Start navigation menu-->
    <div class="">
        <nav class="navbar navbar-custom navbar-fixed-top">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle navbar-toggle-custom" data-toggle="collapse" data-target="#menu">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="#slideshow" class="navbar-brand navbar-brand-custom">
                </a>
            </div>
            <div class="collapse navbar-collapse" id="menu">
                <ul class="nav navbar-nav navbar-nav-custom ">
                    <li><a href="#brand">بازاریابی</a></li>
                    <li><a href="#insurance">بیمه</a></li>
                    <li><a href="#financial">امور مالیاتی</a></li>
                    <li><a href="#company">ثبت امور شرکتی</a></li>
                    <li><a href="#develop">توسعه فردی</a></li>
                    <li><a href="#resume">سوابق و رزومه ها</a></li>
                    <li><a href="#gallery">گالری</a></li>
                    <li><a href="#link">لینک ها</a></li>
                    <li><a href="#about">درباره ما</a></li>
                    <li><a href="#contact">تماس با ما</a></li>
                </ul>
            </div>
        </nav>
    </div>
    <!--End navigation menu-->
        @RenderBody()
    <!--Start footer-->
    <footer class="container-fluid footer">
        <div class="text-center">
            <h4 class="wow fadeInUp">تمامی حقوق این سایت برای راهبران اندیشه محفوظ است</h4>
            <h5>طراحی توسط یک دیزاینر</h5>
        </div>
    </footer>
    <!--End footer-->
<script type="text/javascript" src="~/Content/js/plugin.js"></script>
<script type="text/javascript" src="~/Content/js/main.js"></script>ِ
<script type="text/javascript" src="~/Content/js/script.js"></script>ِ
</body>
</html>

Rahbaran Andishe/Views/Shared/_Layout_Additional.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link type="text/css" rel="stylesheet" href="~/Content/css/plugin.css">
    <link type="text/css" rel="stylesheet" href="~/Content/css/main.css">
    <title>بازاریابی اینترنتی</title>
</head>
<body>
    <!--Start navigation-->
    <nav class="navbar navbar-custom">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle navbar-toggle-custom" data-toggle="collapse"
                        data-target="#menu">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="menu">
                <address class="pull-left">
                    <span class="fa fa-phone "></span>
                    <p class="pull-left"> تلفن تماس : 09384953091 </p>
                </address>
                <ul class="nav navbar-nav navbar-nav-custom ">
                    <li><a href="@Url.Action("Index","Home")" target="_blank"> صفحه اصلی</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <!--End navigation-->

    @RenderBody()

    <!--Start footer content section-->
    <section class="footer-content">
        <div class="container ">
            <div class="row">
                <div class="col-xs-12 col-sm-6 col-md-6 footer-padding">
                    <div class="public-right">
                        <h1>راهبران اندیشه</h1>
                        <span class="fa fa-info pull-right"></span>
                        <p>اطلاع رسانی در زمینه استفاده از متد های نوین فناوری اطلاعات و ارتباطات در مشاغل متفاوت </p>
                        <span class="fa fa-info pull-right"></span>
                        <p>پیشنهاد راهکارهای جدید جهت ارتقا فروش بیشتر با ابزارهای تجارت الکترونیک </p>
                        <span class="fa fa-info pull-right"></span>
                        <p> آدرس دفتر : کرج - میدان آزادگان - بلوار مطهری - جنب اطلس پود</p>
                        <span class="fa fa-phone pull-right"></span>
                        <p>تلفن تماس : 09384953091</p>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-5 col-md-offset-1 footer-padding">
                    <div class="public-left">
                        <h1>راهبران اندیشه در فضای مجازی</h1>
                        <div class="social ">
                            <a href="#">
                                <span class="fa fa-instagram"></span>
                            </a>
                            <a href="#">
                                <span class="fa fa-paper-plane"></span>
                            </a>
                            <a href="#">
                                <span class="fa fa-facebook"></span>
                            </a>
                            <p class="email">ایمیل : rahbaran.andisheh@gmail.com<span class="fa fa-envelope pull-right"></span></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--End footer content section-->
    <footer class="container-fluid primary-footer">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12  ">
                <div class="footer-right-container">
                    <h4 class="text-center">تمامی حقوق این سایت برای راهبران اندیشه محفوظ است</h4>
                    <a href="https://www.instagram.com/one___designer/" class="text-center center-block">
                        طراحی توسط یک دیزاینر
                    </a>
                </div>
            </div>
        </div>
    </footer>

    <script type="text/javascript" src="~/Content/js/plugin.js" />
    <script type="text/javascript" src="~/Content/js/main.js" />
    
</body>
</html>